In [204]:
#import the necessary module
import re # imported  to use regular expressions
import pickle #Pickling is a way to convert a python object (list, dict, etc.) into a character stream
import pandas as pd # Python library to deal with sequential and tabular data
import numpy as np #numpy library which provides objects for multi-dimensional arrays.
from numpy import nan

In [205]:
import nltk #natural language toolkit
from nltk.corpus import stopwords #removing stopwords with NLTK in python
from nltk.stem import WordNetLemmatizer #to apply lemmatization

In [206]:
from sklearn.feature_extraction.text import TfidfVectorizer # Convert a collection of raw documents to a matrix of TF-IDF features.
from sklearn.tree import DecisionTreeClassifier #for decision tree classification
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score,average_precision_score,recall_score #Import scikit-learn metrics module for evaluation metrics calculation
from sklearn.model_selection import train_test_split #splitting data arrays into two subsets: for training data and for testing data
from sklearn import model_selection, naive_bayes, svm #naive bayes and svm algorithm
from sklearn.neighbors import KNeighborsClassifier #knn algorithm
from sklearn.ensemble import RandomForestRegressor,RandomForestClassifier #random forest algorithm
from sklearn.linear_model import SGDClassifier# SGD algorithm


In [207]:
# read the file which contains 3130 dataset as a data frame
df= pd.read_csv('Dataset_3130_after_webscraping.csv')  

In [208]:
#convert data frame into a list 

C = (df['Content']).tolist()

L = (df['Label']).tolist()

In [209]:
#PREPROCESSING
def preprocess(col):
    col_l = []
    for r in col:
        #print(r)
        try:
            a = r.lower() # returns a copy of the string in which all case-based characters have been lowercased.
            a = a.replace("'s", "")
            #a = a.replace(["\n"], "hjfgjh")
            #regular expression operations, specify a regular expression pattern in the first argument, a   new string in the second argument, and a string to be processed in the third argument
            a = re.sub('[^a-zA-Z0-9 \n\.]', '',a)
            a = re.sub('[:.\n\t]', '',a)
            a = re.sub('[?:!.+,]]][]]//;]', '',a) 
            
            col_l.append(a)
        except:
            #print("No header found")
            col_l.append("No Header")
            pass

    # Downloading punkt and wordnet from NLTK
    nltk.download('punkt')
    print("------------------------------------------------------------")
    nltk.download('wordnet')# used to find the meaning of words
    
    wordnet_lemmatizer = WordNetLemmatizer()
    
    nltk.download('stopwords')#removing useless data(the,a,an,in)
    
    lemmatized_text_list = []

    for s in col_l:
        #print(s)
        # Create an empty list containing lemmatized words
        lemmatized_list = []

        # Save the text and its words into an object
        #text = df.loc[row]['Content_Parsed_4']
        text_words = s.split(" ")

        # Iterate through every word to lemmatize
        for word in text_words:
            lemmatized_list.append(wordnet_lemmatizer.lemmatize(word, pos="v"))#considering only verb

        # Join the list
        lemmatized_text = " ".join(lemmatized_list)

        # Append to the list containing the texts
        lemmatized_text_list.append(lemmatized_text)
    
    new_lemmatized_text_list = []
    for x in lemmatized_text_list:
        new_lemmatized_text_list.append(" ".join(x.split())) 
    
    pl = pd.Series(new_lemmatized_text_list)
   # pl = pd.Series(col_l)
    stop_words = list(stopwords.words('english'))
    
    for stop_word in stop_words:
        regex_stopword = r"\b" + stop_word + r"\b"
        #pl = pd.Series(col_l)
   
        pl = pl.str.replace(regex_stopword, '')
        
    
    return pl.tolist()

In [210]:
#apply preprocessing for the content C
con = preprocess(C)
#print(con)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Jojy\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Jojy\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Jojy\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


------------------------------------------------------------


In [211]:
len(con)

3130

In [212]:
L

['iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-pr

In [213]:
len(L)

3130

In [214]:
label = []#initializing the list

In [215]:
#’iot-project’ replacing with 1 and ‘non-iot-project’ replacing with 0
for i in L:
    if i == 'iot-project' or i == 'Iot-Project':
        label.append(1)
        
    elif i == 'non-iot-project':
        label.append(0)
 
        
   

In [216]:
len(label)

3130

In [217]:
la2 = pd.Series(label) #it contains the label and it is considering as y
la2

0       1
1       1
2       1
3       1
4       1
       ..
3125    0
3126    0
3127    0
3128    0
3129    0
Length: 3130, dtype: int64

In [218]:
 df = pd.DataFrame({"Content":con})# content is saved in dataframe and it is considering as X

In [219]:
df

Content
0     connect  modbus energy meter   arduino  monito...
1     remote control  laser   use  multiple argons r...
2     know   go check   trek get call without stall ...
3      simple tutorial  connect microbit  azure  les...
4     tire  joystick control   phone use l298n ardui...
...                                                 ...
3125   website collect personal data  use cookies  i...
3126   website collect personal data  use cookies  i...
3127  reduce data   data center    mentality   past ...
3128  four fundamental device management requirement...
3129  requirements   secure internet  things system ...

[3130 rows x 1 columns]

In [220]:
#####################################  Training Module Starts  #########################################

#X value is content and y value is label .we are spliting 15%(470) of dataset as testing and 85% (2660)data is for training

In [221]:
X_train, X_test, y_train, y_test = train_test_split(df, la2, test_size=0.15, random_state=8)

In [222]:

X_test

Content
2133   want  make  goodlooking nonpermanent way  mar...
2541  hi guy   go  publish  instructables    long ti...
1974  add  twinkle   holiday stock   lilypad lilytin...
1496   grow backyard blackberry  raspberries     alw...
2085  dont   love  freshness  spring  instructable  ...
...                                                 ...
1405   model  base   contemporary   time plan   ship...
1524   youre like   wish  enjoy  morning coffee  rel...
2171    day  run   coffee roasters  walk around town...
1035  autonomous water system base  wemos d1 mini co...
2343  ive always marvel   charm  take something ordi...

[470 rows x 1 columns]

In [223]:
y_train

541     1
148     1
798     1
1088    1
1854    0
       ..
2181    0
2409    0
2033    0
1364    1
451     1
Length: 2660, dtype: int64

In [224]:
# Initializing the parameters for Tfidf vectorization:
ngram_range = (1,2)
min_df = 10
max_df = 1.
max_features =300

In [225]:
#Tfidf vectorization: Transforms text to feature vectors
tf = TfidfVectorizer(encoding='utf-8',
                        ngram_range=ngram_range,
                        stop_words=None,
                        lowercase=False,
                        max_df=max_df,
                        min_df=min_df,
                        max_features=max_features,
                        norm='l2',
                        sublinear_tf=True)

In [226]:
# Fit the model

tf_transformer = tf.fit(X_train['Content'])
print(tf_transformer)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=False, max_df=1.0, max_features=300,
                min_df=10, ngram_range=(1, 2), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=True, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)


In [227]:
# Dump the file
pickle.dump(tf_transformer, open("tfidf1.pkl", "wb"))
#load the file
tf1 = pickle.load(open("tfidf1.pkl", 'rb'))

In [228]:
#converting the trained content to vector format
features_train= tf1.transform(X_train['Content']).toarray()
print(features_train)




[[0.         0.         0.12915052 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.11788557 0.         0.        ]
 [0.         0.         0.13334129 ... 0.         0.         0.        ]
 ...
 [0.12018515 0.13452943 0.         ... 0.         0.         0.        ]
 [0.12565716 0.08307283 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.11049435 0.         0.        ]]


In [229]:
#converting the testing content to vector format
features_test = tf1.transform(X_test['Content']).toarray()
print(features_test)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.09351063 0.         0.        ]
 [0.         0.         0.         ... 0.         0.06079141 0.        ]
 ...
 [0.         0.         0.10314554 ... 0.         0.06930043 0.        ]
 [0.         0.         0.         ... 0.06930961 0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [230]:


#####################################  Training Module Ends  #########################################

In [231]:
################################## DECISION TREE  Classifier###############################################

In [232]:
#DTC =DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=5,max_features=None, max_leaf_nodes=10, min_samples_leaf=5,min_samples_split=2, min_weight_fraction_leaf=0.0,random_state=None, splitter='random')
DTC = DecisionTreeClassifier(random_state=20,min_samples_leaf=30)
DTC.fit(features_train, y_train)


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=30, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=20, splitter='best')

In [233]:
# save the model to disk
filename = 'finalized_model.sav'
pickle.dump(DTC, open(filename, 'wb'))

In [234]:
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
result1 = loaded_model.score(features_train, y_train)
result = loaded_model.score(features_test, y_test)

print("Training Accuacy",result1)
print("Testing Accuacy",result)
#=loaded_model.predict_proba(features_test[:5])
#print(y)

Training Accuacy 0.9984962406015038
Testing Accuacy 0.9957446808510638


In [235]:
#predicting the testing dataset(470)
DTC_pred = loaded_model.predict(features_test)
DTC_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,

In [236]:
#displaying the confusion_matrix
matrix = confusion_matrix(y_test, DTC_pred)
print(matrix)


[[270   0]
 [  2 198]]


In [237]:
#displaying precision,recall and f1 score
report = classification_report(y_test, DTC_pred)
print(report)

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       270
           1       1.00      0.99      0.99       200

    accuracy                           1.00       470
   macro avg       1.00      0.99      1.00       470
weighted avg       1.00      1.00      1.00       470



In [238]:
##############NAIVE BAYES######################

In [239]:
Naive = naive_bayes.MultinomialNB(alpha=0.0001)
Naive.fit(features_train, y_train)



MultinomialNB(alpha=0.0001, class_prior=None, fit_prior=True)

In [240]:
# save the model to disk
filename_naive = 'finalized_naive.sav'
pickle.dump(Naive, open(filename_naive, 'wb'))

In [241]:
# load the model from disk
loaded_naive = pickle.load(open(filename_naive, 'rb'))
result = loaded_naive.score(features_train, y_train)
result1 = loaded_naive.score(features_test, y_test)
print("Training Accuacy",result)
print("Testing Accuacy",result1)

Training Accuacy 0.925187969924812
Testing Accuacy 0.9212765957446809


In [242]:

Naive_pred = loaded_naive.predict(features_test)
Naive_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,

In [243]:
matrix = confusion_matrix(y_test, Naive_pred)
print(matrix)
report = classification_report(y_test, Naive_pred)
print(report)


[[234  36]
 [  1 199]]
              precision    recall  f1-score   support

           0       1.00      0.87      0.93       270
           1       0.85      0.99      0.91       200

    accuracy                           0.92       470
   macro avg       0.92      0.93      0.92       470
weighted avg       0.93      0.92      0.92       470



In [244]:
SVM = svm.SVC(C=0.1,probability=True,kernel='linear')
SVM.fit(features_train, y_train)



SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=True, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [245]:
# save the model to disk
filename_svm = 'finalized_svm.sav'
pickle.dump(SVM, open(filename_svm, 'wb'))

In [246]:
# load the model from disk
loaded_svm = pickle.load(open(filename_svm, 'rb'))
result = loaded_svm.score(features_train, y_train)
result1 = loaded_svm.score(features_test, y_test)
print("Training Accuacy",result)
print("Testing Accuacy",result1)
#y=loaded_svm.predict_proba(features_test)
#print(y)

Training Accuacy 0.9917293233082707
Testing Accuacy 0.9808510638297873


In [247]:
svm_pred = loaded_svm.predict(features_test)
svm_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,

In [248]:
matrix = confusion_matrix(y_test, svm_pred)
print(matrix)
report = classification_report(y_test, svm_pred)
print(report)


[[261   9]
 [  0 200]]
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       270
           1       0.96      1.00      0.98       200

    accuracy                           0.98       470
   macro avg       0.98      0.98      0.98       470
weighted avg       0.98      0.98      0.98       470



In [249]:
knn = KNeighborsClassifier(n_neighbors=7,weights='distance')
knn.fit(features_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='distance')

In [250]:
# save the model to disk
filename_knn = 'finalized_knn.sav'
pickle.dump(knn, open(filename_knn, 'wb'))

In [251]:
# load the model from disk
loaded_knn = pickle.load(open(filename_knn, 'rb'))
result = loaded_knn.score(features_train, y_train)
result1= loaded_knn.score(features_test, y_test)
print("Training  Accuacy",result)
print("Testing Accuacy",result1)

Training  Accuacy 1.0
Testing Accuacy 0.9808510638297873


In [252]:
knn_pred = loaded_knn.predict(features_test)
knn_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,

In [253]:
matrix = confusion_matrix(y_test, knn_pred)
print(matrix)
report = classification_report(y_test, knn_pred)
print(report)

[[270   0]
 [  9 191]]
              precision    recall  f1-score   support

           0       0.97      1.00      0.98       270
           1       1.00      0.95      0.98       200

    accuracy                           0.98       470
   macro avg       0.98      0.98      0.98       470
weighted avg       0.98      0.98      0.98       470



In [254]:
#clf = SGDClassifier(loss="log", penalty="l1", max_iter=100)
SGD = SGDClassifier(random_state=8,loss="log")
SGD.fit(features_train, y_train)


SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='log', max_iter=1000,
              n_iter_no_change=5, n_jobs=None, penalty='l2', power_t=0.5,
              random_state=8, shuffle=True, tol=0.001, validation_fraction=0.1,
              verbose=0, warm_start=False)

In [255]:
# save the model to disk
filename_sgd = 'finalized_sgd.sav'
pickle.dump(SGD, open(filename_sgd, 'wb'))

In [256]:
# load the model from disk
loaded_sgd = pickle.load(open(filename_sgd, 'rb'))
result1 = loaded_sgd.score(features_train, y_train)
result = loaded_sgd.score(features_test, y_test)
print("Training Accuacy",result1)
print("Testing Accuacy",result)
#y=loaded_sgd.predict_proba(features_test[:5])
#print(y)

Training Accuacy 0.9984962406015038
Testing Accuacy 0.9914893617021276


In [257]:
sgd_pred = loaded_sgd.predict(features_test)
sgd_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,

In [258]:
matrix = confusion_matrix(y_test, sgd_pred)
print(matrix)
report = classification_report(y_test, sgd_pred)
print(report)

[[268   2]
 [  2 198]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       270
           1       0.99      0.99      0.99       200

    accuracy                           0.99       470
   macro avg       0.99      0.99      0.99       470
weighted avg       0.99      0.99      0.99       470



In [259]:
 
random = RandomForestClassifier(n_estimators=2,max_features='log2',random_state=47,max_depth=20,min_samples_leaf=20)
#random = RandomForestClassifier(n_estimators=20)
#regressor = RandomForestRegressor(n_estimators=2, max_depth=None,min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='auto', max_leaf_nodes=None,bootstrap=True, oob_score=False, n_jobs=1, random_state=None, verbose=0, warm_start=False)

random.fit(features_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=20, max_features='log2',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=20, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=2,
                       n_jobs=None, oob_score=False, random_state=47, verbose=0,
                       warm_start=False)

In [260]:
# save the model to disk
filename_random = 'finalized_random.sav'
pickle.dump(random, open(filename_random, 'wb'))

In [261]:
# load the model from disk
loaded_random = pickle.load(open(filename_random, 'rb'))
result1 = loaded_random.score(features_train, y_train)
result = loaded_random.score(features_test, y_test)
print("Training Accuacy",result1)
print("Testing Accuacy",result)
#y=loaded_random.predict_proba(features_test)
#print(y)

Training Accuacy 0.9924812030075187
Testing Accuacy 0.9829787234042553


In [262]:
random_pred = loaded_random.predict(features_test)
random_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,

In [263]:
matrix = confusion_matrix(y_test, sgd_pred)
print(matrix)
report = classification_report(y_test, sgd_pred)
print(report)

[[268   2]
 [  2 198]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       270
           1       0.99      0.99      0.99       200

    accuracy                           0.99       470
   macro avg       0.99      0.99      0.99       470
weighted avg       0.99      0.99      0.99       470



In [264]:
#Sample code for ensambling
from sklearn.ensemble import VotingClassifier

model = VotingClassifier(estimators=[('lr', knn), ('dt', SVM),('sg', SGD)], voting='hard')
model.fit(features_train, y_train)
model.score(features_test,y_test)


0.9936170212765958